cpdef unpack_primitive(char ifmt, object buf, int offset)
cpdef long unpack_int64(object buf, int offset)
cpdef long unpack_int16(object buf, int offset)
cpdef long unpack_uint32(object buf, int offset)
cpdef bytes pack_message_header(int segment_count, int segment_size, long p)
